// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package proto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson52bdc5a7DecodeGoGameServerProto(in *jlexer.Lexer, out *GetUserInfoRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				in.Delim('[')
				if out.Name == nil {
					if !in.IsDelim(']') {
						out.Name = make([]string, 0, 4)
					} else {
						out.Name = []string{}
					}
				} else {
					out.Name = (out.Name)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Name = append(out.Name, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "base":
			if in.IsNull() {
				in.Skip()
				out.Base = nil
			} else {
				if out.Base == nil {
					out.Base = new(BaseInfo)
				}
				(*out.Base).UnmarshalEasyJSON(in)
			}
		case "cmd":
			out.Cmd = MessageCmd(in.Int32())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson52bdc5a7EncodeGoGameServerProto(out *jwriter.Writer, in GetUserInfoRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Name) != 0 {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v2, v3 := range in.Name {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	if in.Base != nil {
		const prefix string = ",\"base\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(*in.Base).MarshalEasyJSON(out)
	}
	if in.Cmd != 0 {
		const prefix string = ",\"cmd\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int32(int32(in.Cmd))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetUserInfoRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson52bdc5a7EncodeGoGameServerProto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetUserInfoRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson52bdc5a7EncodeGoGameServerProto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetUserInfoRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson52bdc5a7DecodeGoGameServerProto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetUserInfoRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson52bdc5a7DecodeGoGameServerProto(l, v)
}
func easyjson52bdc5a7DecodeGoGameServerProto1(in *jlexer.Lexer, out *GetUserInfoReply) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "userList":
			if in.IsNull() {
				in.Skip()
				out.UserList = nil
			} else {
				in.Delim('[')
				if out.UserList == nil {
					if !in.IsDelim(']') {
						out.UserList = make([]*UserInfo, 0, 8)
					} else {
						out.UserList = []*UserInfo{}
					}
				} else {
					out.UserList = (out.UserList)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *UserInfo
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(UserInfo)
						}
						(*v4).UnmarshalEasyJSON(in)
					}
					out.UserList = append(out.UserList, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson52bdc5a7EncodeGoGameServerProto1(out *jwriter.Writer, in GetUserInfoReply) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.UserList) != 0 {
		const prefix string = ",\"userList\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v5, v6 := range in.UserList {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil {
					out.RawString("null")
				} else {
					(*v6).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GetUserInfoReply) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson52bdc5a7EncodeGoGameServerProto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GetUserInfoReply) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson52bdc5a7EncodeGoGameServerProto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GetUserInfoReply) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson52bdc5a7DecodeGoGameServerProto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GetUserInfoReply) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson52bdc5a7DecodeGoGameServerProto1(l, v)
}
